name: My Action

on:
  pull_request:
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add file to repository
        run: |
          echo "This is a new file." > new_file.txt
          git add new_file.txt
          git commit -m "Add new file"
          git push origin HEAD:main
