name: Check Pull Request Title

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Check Pull Request Title
      if: ${{ github.event.pull_request.title == 'aa' }}
      run: echo "ok"
