name: Check Pull Request Title

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Check Pull Request Title
      if: true ; echo "fail" ; 'aa' == 'aa'
      run: echo "ok"
