name: Use Secrets in GitHub Actions

on: 
  workflow_dispatch:

jobs:
  use_secrets:
    name: Use Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Secret
        run: |
          # Access the secret using ${{ secrets.SECRET_NAME }}
          API_KEY=${{ secrets.API_KEY }}
          echo "The API key is: $API_KEY"
